apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
        app.kubernetes.io/name: productapi
    spec:
      containers:
        - name: productapi-container
          image: aomsh2000/productapi:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productapi-service
spec:
  selector:
    app.kubernetes.io/name: productapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
